### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by Altai-man** [tony-o/perl6-pluggable#14]
```
  ~ zef install Pluggable
===> Searching for: Pluggable
===> Searching for missing dependencies: SVG::Plot::Pie
===> Searching for missing dependencies: SVG
===> Searching for missing dependencies: XML::Writer
===> Testing: XML::Writer
===> Testing [OK] for XML::Writer
===> Testing: SVG
===> Testing [OK] for SVG
===> Testing: SVG::Plot
===> Testing [OK] for SVG::Plot
===> Testing: Pluggable:ver<0.4>:auth<github:tony-o>
[Pluggable] # Failed test at t/02-installation.t line 18
[Pluggable] # You failed 1 test of 1
===> Testing [FAIL]: Pluggable:ver<0.4>:auth<github:tony-o>
Aborting due to test failure: Pluggable:ver<0.4>:auth<github:tony-o> (use --force-test to override)
```

**Comment by Xliff** [comment]
The problem is that SVG::Plot::Pie is listed as a dependency, but zef does _not_ install it until after the tests for Pluggable pass, which they won't since SVG::Plot::Pie isn't yet installed.

Solutions:

1) Pick another plugin that is already installed
2) Force the issue by using zef to install a copy of SVG::Plot::Pie either within the current directory (ala 
 qqx{zef --install-to=. SVG::Plot::Pie} ), or systemwide (which might be rude)
